---
name: Net-SNMP-Mixin-Dot1abLldp
version: 0.10
author:
  - 'Karl Gaissmaier <karl.gaissmaier (at) uni-ulm.de>'
abstract: mixin class for the Link Layer Discovery Protocol
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Net::SNMP: 0
  Net::SNMP::Mixin: 0.11
  Sub::Exporter: 0.978
  perl: 5.6.0
build_requires:
  Module::Build: 0
  Test::More: 0
provides:
  Net::SNMP::Mixin::Dot1abLldp:
    file: lib/Net/SNMP/Mixin/Dot1abLldp.pm
    version: 0.10
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
